### ISSUE TITLE
这个插件能作为函数动态调用吗？

### ISSUE THREAD

**Issue by ouzhou** [xiaohuoni/umi-plugin-authorize#3]
现在你是在umirc.js里调用的，但是业务上的逻辑是先登录，登录后获取到权限，但是你这个插件只在第一次render的时候调用吧，我看了你好几个回复，都没有解决这个问题，patchRoutes 和 render方法似乎都只会在页面加载的时候调用，所以我登录完成后还得存一下localstorage然后刷新页面？

**Comment by ouzhou** [comment]
我想表达的是我的login页面应该是先出来，但是你这个插件是需要发请求后再渲染路由的，于是就成了现有鸡还是先有蛋的问题了

现实项目里面应该没有说你没登录就发起请求获取权限这样的操作，登录页应该会先出来。
所以这个plugin解决了什么问题？
我的方案是 动态侧边栏+监听路由
在baselayout里面判断一下path，如果说没有这个path的权限，直接403

**Comment by xiaohuoni** [comment]
@ouzhou 你好，这个插件只是解决了一个入口问题。你说的问题，我觉得我在umi-antd-pro里面的使用，应该处理了这个问题。你参考一下https://github.com/xiaohuoni/umi-antd-pro/blob/antd-pro/src/pages/Auth.js 如果还不行，你再和我说下。

**Comment by xiaohuoni** [comment]
在pro的https://github.com/ant-design/ant-design-pro/pull/3587 这次提交之后，把权限从layout里面提出来，现在处理这个问题应该变得容易了一点点

**Comment by ouzhou** [comment]
[嗯 其实很早就有人这样干了 不过当时官方没这样实践](https://github.com/ant-design/ant-design-pro/pull/91#issuecomment-346613402)

**Comment by xiaohuoni** [comment]
现在前端框架结合umi，这样处理，个人觉得比较简单理解
