### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by silverWolf818** [xiaohuoni/umi-plugin-authorize#5]
![image](https://user-images.githubusercontent.com/7360502/53960467-5f4b3000-4121-11e9-855e-7d5d639b0b84.png)

**Comment by xiaohuoni** [comment]
路径没写对吗？？

**Comment by yaeSakuras** [comment]
解决了，我把routes放到src里面了，才出问题。有办法放到src里面吗？放到src里面就报错
![image](https://user-images.githubusercontent.com/7360502/53967243-ca9bfe80-412f-11e9-9b38-7543d204e5ce.png)

**Comment by silverWolf818** [comment]
解决了，是我路径写错了，我是放在src里

**Comment by xiaohuoni** [comment]
好的
